name: Continuous Integration - MLflow Project Skilled

on:
  push:
    branches: [main]

jobs:
  re-train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7" # Menyesuaikan rekomendasi environment kelas

      # PERBAIKAN: Menghapus instalasi conda dari pip, dan langsung menginstal library yang dibutuhkan modelling.py
      - name: Install MLflow and Model Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 xgboost pandas scikit-learn matplotlib

      # Jalankan MLflow tracking server di background agar modelling.py bisa terhubung ke http://127.0.0.1:5000
      - name: Start MLflow Tracking Server
        run: |
          cd ./MLProject
          mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5 # Beri waktu agar server menyala

      # Jalankan perintah mlflow run dari dalam folder MLProject
      - name: Run MLflow Project Re-training
        run: |
          cd ./MLProject
          mlflow run . --env-manager local


      # Kunci Penilaian Skilled (3 pts): Simpan artefak run ke GitHub Artifacts
      - name: Upload MLflow Runs Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts-skilled
          path: MLProject/mlruns/
          retention-days: 7
